<template>
    <div class="loading">
      <div class="loadingio-spinner-spinner-dlhmukb28ih">
        <div class="ldio-gxtaziluje8">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
</template>

<script>
export default {
  name: "c-loading",
  data() {
    return {};
  }
};
</script>

<style>
.loading{
    position: fixed;
    top: 0px;
    left: 0px;
    background: #ffffff6b;
    z-index: 999;
    width: 100%;
    height: 100vh;
    display: none;
}
.loading .loadingio-spinner-spinner-dlhmukb28ih{
  position: fixed;
  top: 50%;
  left: 50%;
  transform:translate(-50%,-50%)
}
.loading.showLoading{
  display: block !important;
}
@keyframes ldio-gxtaziluje8 {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-gxtaziluje8 div {
  left: 146.17px;
  top: 74.64px;
  position: absolute;
  animation: ldio-gxtaziluje8 linear 1.0989010989010988s infinite;
  background: #fe718d;
  width: 18.66px;
  height: 37.32px;
  border-radius: 9.33px / 18.66px;
  transform-origin: 9.33px 80.86px;
}
.ldio-gxtaziluje8 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.0073260073260073s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.9157509157509157s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.8241758241758241s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.7326007326007326s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.6410256410256411s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5494505494505495s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.45787545787545786s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3663003663003663s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.27472527472527475s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.18315018315018314s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.09157509157509157s;
  background: #fe718d;
}
.ldio-gxtaziluje8 div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #fe718d;
}
.loadingio-spinner-spinner-dlhmukb28ih {
  width: 311px;
  height: 311px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-gxtaziluje8 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-gxtaziluje8 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>